# Generated by Django 3.1.1 on 2023-05-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enroll.user')),
            ],
            bases=('enroll.user',),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passowrd',
            new_name='password',
        ),
    ]
